fail job on purpose

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,6 +15,10 @@ jobs:
     steps:
       - name: Secret is masked in logs
         run: echo "The secret is ${GREETING}"
+
+      - name: Fail on purpose 
+        echo "about to fail the job" 
+        run: exit 1
         
       - name: Inspect the runner BEFORE checkout
         run: |
